# Generated by Django 4.2.20 on 2025-07-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Address',
            new_name='address',
        ),
    ]
