# Generated by Django 4.2.20 on 2025-07-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_appointment_is_appointment_appointment_id'),
        ('patient', '0003_rename_address_patient_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Patient_notification',
        ),
    ]
