# Generated by Django 4.2.20 on 2025-07-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_is',
            new_name='appointment_id',
        ),
    ]
