# Generated by Django 4.2.20 on 2025-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointment_date',
            field=models.DateTimeField(blank=True, default=-3600, null=True),
        ),
    ]
