# Generated by Django 5.2.3 on 2025-07-21 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_notification_doctor_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 21, 12, 34, 36, 926205, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
